### ISSUE TITLE
Work out how important issue in A&H code is

### ISSUE THREAD

**Issue by jackblun** [jackblun/leisure_git#1]
Tom found a problem in their cleaning code. We need to find out how important this is.

**Comment by lucabrag** [comment]
Is this the issue with the identifiers?

**Comment by tomzohar1** [comment]
As for now the major issues are:

1. Splitting weekend and weekdays: half of the sample is during weekends, which induces a lot of zeros for work time (and in general odd behavior). Splitting the sample could change the results

2. Identifiers: A&H coded their identifiers wrong, in fact when you run their code and look for unique identifiers you find significantly less than the number of observations (in the order of 1%). This stems from the fact that stata collapse big numbers to (e.g.: 14.46e10 instead of 144603478467) if you won't tell it otherwise. When I looked briefly in their analysis it seemed like they don't use the identifiers. Should look closer.

3. Definition of video games is very loose and actually cannot be concretely identified in the data

**Comment by lucabrag** [comment]
Tom: solution to identifier problem was to destring identifier
