### ISSUE TITLE
Imputing Weekly Hours and Weights

### ISSUE THREAD

**Issue by tomzohar1** [jackblun/leisure_git#8]
I agree with A&H that we should look in the weekly hours level so our results will be more meaningful. However I disagree with the way A&H imputed the data on a weekly level. They just multiply an observation by 7 but the weekly weight should be different from weekend weight for different activities.

Simple example: work that is documented during the week (50% of observations, probably since this is when they answer the phone) is usually zero. Thus we will conclude that people that are working, work 0 during that week while they did work...

I am trying to develop a new way to impute weekly hours:
Do calculations on the weekly basics and then weight the results by week and weekend (from the average of task during week over total average of task, and similarly for weekend)

**Comment by jackblun** [comment]
Interesting! I saw that in the code and was wondering about how they did this.

**Comment by lucabrag** [comment]
I think this is a pretty big deal. As a first pass, we should run the A&H analysis (their exact code) using only data from weekdays and see whether the results in their paper change. If they do, that's pretty bad for them. 

Then we should figure out how to handle weekends in our analysis. My understanding is that we should drop them.

**Comment by lucabrag** [comment]
I looked into the issue. Here's what I found:

First of all, ATUS contains weights that adjust for the fact that most observations occur on weekends. After we apply the weights and tabulate the interview_day, we see that the weighted data is basically evenly spread out throughout the week (i.e. equal number of weighted observations on each day of the week).

A&H take it one step further and adjust the weights so that the weighted data is EXACTLY evenly spread out throughout the week (i.e. EXACTLY the same number of weighted observations on each day of the week).

They run all their analysis using the adjusted weights (the weights that they created).

This alleviates the imputation problem. Still weekdays and weekends look very different (even after applying the adjusted_weights). For instance, the average number of hours worked on weekdays in the entire sample is 4.5 and on weekends is 1.3. So weekends still look massively different from weekdays, even after applying the adjusted weights.
